apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: test-svc
  annotations:
    github.com/project-slug: ajax-kuzyk-a/test-svc
spec:
  type: service
  lifecycle: test
  owner: user:ajax-kuzyk-a
