apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: test-svc
  annotations:
    github.com/project-slug: ajax-kuzyk-a/test-svc
  links:    
    - url: https://ajaxsystems.atlassian.net/wiki/search?labels=company-svc%2Crca  
      title: RCA
      icon: warning
    - url: https://kibana.prod-internal.ajax.systems/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:60000),time:(from:now-15m,to:now))&_a=(columns:!(),filters:!(),hideChart:!t,index:company-svc,interval:auto,query:(language:kuery,query:''),sort:!(!('@timestamp',desc)))
      title: Kibana pro
      icon: chat
      type: logs
    - url: https://kibana.stage-internal.ajax.systems/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:60000),time:(from:now-15m,to:now))&_a=(columns:!(),filters:!(),hideChart:!t,index:company-svc,interval:auto,query:(language:kuery,query:''),sort:!(!('@timestamp',desc)))
      title: Kibana stage
      icon: chat
      type: logs
spec:
  type: service
  lifecycle: test
  owner: user:ajax-kuzyk-a
